Repository FinalProject-AIPARK/JenaPark-FE, pull requests merged in 2022-10, with the labels that each got.

#31 Essential done / Voice model #5
  public/upload-icon.png
  src/api/useApi.ts
  src/components/createAvatar/navbar/index.tsx
  src/components/createAvatar/voice/index.tsx
  src/components/createAvatar/voice/voiceModel/index.tsx
  src/layout/NavigationBar/UserNavbarLayout.tsx
  src/layout/NavigationBar/WorkingNavbarLayout.tsx
  src/layout/SearchVoiceModelLayout.tsx
  src/layout/Voice/SearchVoiceModelLayout.tsx
  src/layout/Voice/VoiceModelFilterButton.tsx
  src/layout/Voice/VoiceModelListLayout.tsx
  src/layout/Voice/VoiceUploadModal.tsx
  src/layout/Voice/VoiceWorkingButtonLayout.tsx
  src/layout/VoiceModelFilterButton.tsx
  src/main.tsx
  src/store/store.ts
  src/store/voice/voiceSlice.ts
Labels: feature, component

#32 Modify header design #30
  src/App.tsx
  src/components/Header/ProjectHeader/index.tsx
  src/layout/ProjectVideoHeader.tsx
  src/layout/ProjectVoiceHeader.tsx
  src/layout/SoundPlayer.tsx
Labels: fix, style

#34 Voice option #6
  public/breathOption-icon.png
  public/questionMark-icon.png
  public/volume-icon.png
  src/api/useApi.ts
  src/components/createAvatar/index.tsx
  src/components/createAvatar/navbar/index.tsx
  src/components/createAvatar/voice/voiceModel/index.tsx
  src/components/createAvatar/voice/voiceOption/index.tsx
  src/layout/Voice/SearchVoiceModelLayout.tsx
  src/layout/Voice/VoiceModelListLayout.tsx
  src/layout/Voice/VoiceOptionDetailLayout.tsx
  src/layout/Voice/VoiceOptionTitleLayout.tsx
  src/main.tsx
  src/store/store.ts
  src/store/voice/voiceSlice.ts
  src/store/workingProject/projectControlSlice.ts
Labels: feature, component, style

#37 Create React Cookie
  package.json
  src/App.tsx
  src/api/useApi.ts
  src/components/signIn/SignInForm.tsx
  src/layout/AvatarChooseStyle.tsx
  src/layout/AvatarOptionStyle.tsx
  src/main.tsx
  src/pages/Home.tsx
  yarn.lock
Labels: feature

#38 #36 💇style: Edit Model list Component
  src/layout/Voice/VoiceModelFilterButton.tsx
  src/layout/Voice/VoiceModelListLayout.tsx
  src/layout/Voice/VoiceUploadModal.tsx
Labels: style

#52 Input text #7
  src/components/createAvatar/contents/index.tsx
  src/components/createAvatar/contents/inputText/index.tsx
  src/components/createAvatar/index.tsx
  src/layout/ProjectInputText.tsx
  src/store/voice/voiceSlice.ts
Labels: feature, component, style

#61 Preview avatar #53
  public/PreviewAvatar-icon.png
  src/components/createAvatar/contents/index.tsx
  src/components/createAvatar/contents/inputText/index.tsx
  src/layout/ProjectPreviewAvatar.tsx
  src/main.tsx
  src/store/Avatar/avatarSlice.ts
  src/store/workingProject/projectControlSlice.ts
Labels: feature, component, style

#65 fix: Project history #54
  src/api/useApi.ts
  src/components/History/index.tsx
Labels: fix

#66 로그아웃 기능 구현 #1
  public/previewAvatar-icon.png
  src/api/useApi.ts
  src/components/LandingPage/index.tsx
  src/components/signIn/SignInForm.tsx
  src/layout/ProjectPreviewAvatar.tsx
  src/layout/RendingHeader.tsx
  src/layout/avatar/AvatarChooseLayout.tsx
  src/layout/avatar/AvatarOptionStyle.tsx
  src/store/Auth.ts
  src/store/authSlice.ts
  src/store/cookie.ts
Labels: feature

#69 File Issue...Video history #63
  public/ dummyVideo.mp4
  src/api/useApi.ts
  src/components/History/index.tsx
  src/layout/HistoryProjectLayout.tsx
  src/layout/HistoryVideoLayout.tsx
  src/layout/VideoDownloadModal.tsx
Labels: feature, component, style

#70 추가 가능: User navigation bar #4
  src/api/useApi.ts
  src/components/createAvatar/index.tsx
  src/components/createAvatar/navbar/index.tsx
  src/layout/NavigationBar/UserNavbarLayout.tsx
  src/main.tsx
  src/store/Auth.ts
  src/store/workingProject/projectControlSlice.ts
Labels: feature

#67 Add header #62
  src/api/useApi.ts
  src/components/Header/ProjectHeader/ProjectVideoHeader/index.tsx
  src/components/Header/ProjectHeader/ProjectVoiceHeader/index.tsx
  src/components/Header/ProjectHeader/index.tsx
  src/components/Header/SoundPlayer/index.tsx
  src/components/Header/index.tsx
  src/layout/ProjectHeader.tsx
  src/layout/ProjectVideoHeader.tsx
  src/layout/SoundPlayer.tsx
Labels: refactoring, style

#71 Landing page #3
  src/layout/LandingPageStyle.tsx
Labels: feature, component, style

#73 #72 🧯hotfix: Init Project Data
  src/store/workingProject/projectControlSlice.ts
Labels: fix

#74 로그인 폼 #1
  public/background.svg
  public/icon/hidePassword.svg
  public/icon/showPassword.svg
  public/images/googleLogin.svg
  public/images/kakaoLogin.svg
  src/App.tsx
  src/components/Header/index.tsx
  src/components/signIn/SignInForm.tsx
  src/components/signIn/style.ts
  src/components/signUp/SignUpForm.tsx
  src/components/signUp/style.ts
  src/layout/RendingHeader.tsx
  src/main.tsx
  src/pages/Account.tsx
  src/pages/MyPage.tsx
  src/pages/NotFound.tsx
  src/pages/SignIn.tsx
Labels: feature, configuration, style

#77 Video history #68
  public/close-icon.png
  src/api/useApi.ts
  src/components/History/index.tsx
  src/layout/HistoryProjectLayout.tsx
  src/layout/HistoryVideoLayout.tsx
  src/layout/VideoDownloadModal.tsx
Labels: feature, component

#79 History 스타일 수정 #78
  src/api/useApi.ts
  src/components/History/index.tsx
  src/layout/HistoryProjectLayout.tsx
  src/layout/HistoryVideoLayout.tsx
Labels: style

#80 feat: Delete Project #76
  src/api/useApi.ts
  src/components/History/index.tsx
  src/layout/HistoryProjectLayout.tsx
Labels: feature

#86 텍스트 입력 합성에 필요한 Project id data #85
  src/components/createAvatar/voice/voiceModel/index.tsx
  src/components/createAvatar/voice/voiceOption/index.tsx
  src/layout/Voice/VoiceModelFilterButton.tsx
  src/layout/Voice/VoiceModelListLayout.tsx
  src/layout/Voice/VoiceUploadModal.tsx
  src/store/voice/voiceSlice.ts
  src/store/workingProject/projectControlSlice.ts
Labels: feature

#88 Redux voice data 87
  src/api/useApi.ts
  src/components/createAvatar/voice/voiceOption/index.tsx
  src/store/voice/voiceSlice.ts
Labels: feature

#82 Footer #51
  public/images/Vector.png
  src/components/Footer/LandingFooter/index.tsx
  src/components/Footer/ProjectFooter/index.tsx
  src/components/Header/LendingHeader/index.tsx
  src/components/Header/RendingHeader/index.tsx
  src/components/Header/index.tsx
  src/components/LandingPage/index.tsx
  src/components/createAvatar/index.tsx
  src/layout/LendingFooter.tsx
  src/layout/LendingHeader.tsx
  src/layout/ProjectFooter.tsx
Labels: feature, component, style

#89 Project init data #81
  src/components/createAvatar/contents/inputText/index.tsx
  src/components/createAvatar/index.tsx
  src/components/createAvatar/voice/index.tsx
  src/components/createAvatar/voice/voiceModel/index.tsx
  src/components/createAvatar/voice/voiceOption/index.tsx
  src/layout/Voice/VoiceOptionTitleLayout.tsx
  src/layout/Voice/VoiceWorkingButtonLayout.tsx
  src/store/voice/voiceSlice.ts
  src/store/workingProject/projectControlSlice.ts
Labels: feature

#92 #13 💇style: Sign up form
  src/components/signIn/SignInForm.tsx
  src/components/signIn/style.ts
  src/components/signUp/SignUpForm.tsx
  src/components/signUp/style.ts
Labels: style

#93 Avatar choose #12
  public/plus-icon.png
  src/components/createAvatar/avatar/chooseAvatar/index.tsx
  src/layout/avatar/AvatarChooseLayout.tsx
  src/store/Avatar/avatarSlice.ts
Labels: feature, style

#94 Add header button function #84
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/jenna-park-issue-template.md
  src/api/useApi.ts
  src/layout/ProjectHeader.tsx
  src/layout/SoundPlayer.tsx
Labels: feature

#96 Add Panding Page Button Function And Change Style #95
  src/layout/LandingPageStyle.tsx
Labels: feature, style

#108 Addproject data #107
  src/api/useApi.ts
  src/components/createAvatar/contents/inputText/index.tsx
  src/components/createAvatar/index.tsx
  src/components/createAvatar/voice/voiceOption/index.tsx
  src/layout/ProjectPreviewAvatar.tsx
  src/store/workingProject/projectControlSlice.ts
Labels: feature

#112 Fix: Select model UI #111
  src/components/createAvatar/voice/voiceModel/index.tsx
  src/layout/Voice/VoiceOptionTitleLayout.tsx
Labels: fix

#114 History title 수정 블러 동작 #113
  src/components/History/index.tsx
  src/layout/ErrorBigLayout.tsx
  src/layout/HistoryProjectLayout.tsx
  src/layout/VideoDownloadModal.tsx
Labels: feature

#106 Avatar option #11
  src/api/useApi.ts
  src/components/createAvatar/avatar/avatarOption/index.tsx
  src/layout/avatar/AvatarOptionLayout.tsx
Labels: feature

#118 Landing page design modification
  src/layout/LandingPageStyle.tsx
  src/layout/LendingFooter.tsx
  src/layout/LendingHeader.tsx
  src/layout/ProjectHeader.tsx
Labels: style

#121 #120 ✈️test: All Listen Voice File Api
  src/api/useApi.ts
  src/layout/ProjectHeader.tsx
  src/layout/SoundPlayer.tsx
Labels: test

#122 #120 💧fix: All Listen Voice File Api
  src/api/useApi.ts
  src/layout/SoundPlayer.tsx
Labels: fix

#130 #117 💩rename: Change Directory Name
  src/components/footer/landingFooter/index.tsx
  src/components/footer/projectFooter/index.tsx
  src/components/header/landingHeader/index.tsx
  src/components/header/projectHeader/index.tsx
  src/components/header/soundPlayer/index.tsx
  src/components/history/index.tsx
  src/components/landingPage/index.tsx
  src/layout/navigationBar/UserNavbarLayout.tsx
  src/layout/navigationBar/WorkingNavbarLayout.tsx
  src/layout/voice/SearchVoiceModelLayout.tsx
  src/layout/voice/VoiceModelFilterButton.tsx
  src/layout/voice/VoiceModelListLayout.tsx
  src/layout/voice/VoiceOptionDetailLayout.tsx
  src/layout/voice/VoiceOptionTitleLayout.tsx
  src/layout/voice/VoiceUploadModal.tsx
  src/layout/voice/VoiceWorkingButtonLayout.tsx
  src/store/avatar/avatarSlice.ts
Labels: fix

#132 최종 영상 합성 기능 #123
  src/api/useApi.ts
  src/components/createAvatar/avatar/chooseAvatar/index.tsx
  src/components/createAvatar/contents/editText/index.tsx
  src/components/createAvatar/contents/inputText/index.tsx
  src/components/createAvatar/voice/voiceModel/index.tsx
  src/layout/ErrorBigLayout.tsx
  src/layout/ProjectHeaderSoundPlayer.tsx
  src/layout/projectContents/ProjectEditTextLayout.tsx
  src/layout/projectContents/ProjectHeaderLayout.tsx
  src/store/editText/EditTextSlice.ts
Labels: feature

#136 #133 fix: Audio Download
  src/layout/ProjectHeaderSoundPlayer.tsx
  src/layout/projectContents/ProjectHeaderLayout.tsx
Labels: fix
